---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elk
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300

---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
spec:
  selector:
    app: logstash
  ports:
  - name: tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: beats
    port: 5044
    protocol: TCP
    targetPort: 5044

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elk
  labels:
    component: elk
    role: kibana
spec:
  selector:
    app: kibana
  ports:
  - name: http
    port: 80
    targetPort: 5601
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  namespace: elk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - image: elasticsearch:latest
        name: elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        command: ["/docker-entrypoint.sh", "elasticsearch", "-Des.network.host=0.0.0.0"]

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash-deployment
  namespace: elk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: logstash:latest
        name: logstash
        ports:
        - containerPort: 5000
        - containerPort: 5044
        command: ["/bin/bash", "-c", "set -x; /docker-entrypoint.sh logstash -e \"input { tcp { port => 5000 } beats { port => 5044 } } output { elasticsearch { hosts => '${ELASTICSEARCH_SERVICE_HOST}:9200' } }\""]
        # command: ["/bin/bash", "-c", "set -x; gosu logstash -e \"input { tcp { port => 5000 } beats { port => 5044 } } output { elasticsearch { hosts => '${ELASTICSEARCH_SERVICE_HOST}:9200' } }\""]

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-deployment
  namespace: elk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - image: kibana:latest
        name: kibana
        ports:
        - containerPort: 5601
